"""add search query rewritten_query

Revision ID: 5b4d5f6d215d
Revises: e3e713268eeb
Create Date: 2026-09-12 21:22:15.723566
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5b4d5f6d215d'
down_revision: str | None = 'e3e713268eeb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_queries', sa.Column('rewritten_query', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_queries', 'rewritten_query')
    # ### end Alembic commands ###
