"""release fingerprint of soft-deleted papers

Revision ID: 7359b44a3938
Revises: f2501d50f1ec
Create Date: 2026-09-11 21:42:41.824556
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7359b44a3938'
down_revision: str | None = 'f2501d50f1ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('papers_fingerprint_key'), 'papers', type_='unique')
    op.create_index('uq_papers_fingerprint_live', 'papers', ['fingerprint'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Restores the pre-release global UNIQUE(papers.fingerprint) -- the state
    # where a soft-deleted row occupied its fingerprint forever. That global
    # constraint can only be created when NO two rows share a fingerprint, and
    # the whole point of this release was that soft-deleted duplicates exist:
    # hard-purge them first (they are already marked deleted; the data lives in
    # MinIO and OpenSearch cleanup is the operator's call). Without this the
    # create_unique_constraint below fails on the very rows the release was
    # about (review 2026-10-05, P3 -- the old downgrade was self-contradictory).
    op.execute("DELETE FROM papers WHERE deleted_at IS NOT NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_papers_fingerprint_live', table_name='papers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('papers_fingerprint_key'), 'papers', ['fingerprint'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
