"""release fingerprint of soft-deleted papers

Revision ID: 7359b44a3938
Revises: f2501d50f1ec
Create Date: 2026-09-11 21:42:41.824556
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7359b44a3938'
down_revision: str | None = 'f2501d50f1ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('papers_fingerprint_key'), 'papers', type_='unique')
    op.create_index('uq_papers_fingerprint_live', 'papers', ['fingerprint'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_papers_fingerprint_live', table_name='papers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('papers_fingerprint_key'), 'papers', ['fingerprint'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
