"""create core paperbox schema

Revision ID: f2501d50f1ec
Revises: 
Create Date: 2026-09-11 16:10:57.460343
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f2501d50f1ec'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('orcid', sa.String(length=64), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_authors_name', 'authors', ['name'], unique=False)
    op.create_table('paper_tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('venues',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('papers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('venue_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index('ix_papers_arxiv_id', 'papers', ['arxiv_id'], unique=False)
    op.create_index('ix_papers_created_at', 'papers', ['created_at'], unique=False)
    op.create_index('ix_papers_doi', 'papers', ['doi'], unique=False)
    op.create_index('ix_papers_status', 'papers', ['status'], unique=False)
    op.create_index('ix_papers_year', 'papers', ['year'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paper_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('kind', sa.String(length=32), server_default=sa.text("'ingest'"), nullable=False),
    sa.Column('stage', sa.String(length=32), server_default=sa.text("'received'"), nullable=False),
    sa.Column('progress', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_created_at', 'ingestion_jobs', ['created_at'], unique=False)
    op.create_index('ix_ingestion_jobs_paper_id', 'ingestion_jobs', ['paper_id'], unique=False)
    op.create_index('ix_ingestion_jobs_stage', 'ingestion_jobs', ['stage'], unique=False)
    op.create_table('paper_authors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('is_corresponding', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'author_id', name='uq_paper_authors_paper_author'),
    sa.UniqueConstraint('paper_id', 'author_order', name='uq_paper_authors_order')
    )
    op.create_index('ix_paper_authors_author_id', 'paper_authors', ['author_id'], unique=False)
    op.create_table('paper_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('subsection', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_end IS NULL OR page_start IS NULL OR page_end >= page_start', name='ck_paper_chunks_page_range'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'chunk_index', name='uq_paper_chunks_paper_index')
    )
    op.create_index('ix_paper_chunks_paper_id', 'paper_chunks', ['paper_id'], unique=False)
    op.create_index('ix_paper_chunks_paper_section', 'paper_chunks', ['paper_id', 'section'], unique=False)
    op.create_table('paper_files',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=32), server_default=sa.text("'original'"), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_files_paper_id', 'paper_files', ['paper_id'], unique=False)
    op.create_index('ix_paper_files_sha256', 'paper_files', ['sha256'], unique=False)
    op.create_table('papers_tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['paper_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'tag_id', name='uq_papers_tags_paper_tag')
    )
    op.create_index('ix_papers_tags_tag_id', 'papers_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_papers_tags_tag_id', table_name='papers_tags')
    op.drop_table('papers_tags')
    op.drop_index('ix_paper_files_sha256', table_name='paper_files')
    op.drop_index('ix_paper_files_paper_id', table_name='paper_files')
    op.drop_table('paper_files')
    op.drop_index('ix_paper_chunks_paper_section', table_name='paper_chunks')
    op.drop_index('ix_paper_chunks_paper_id', table_name='paper_chunks')
    op.drop_table('paper_chunks')
    op.drop_index('ix_paper_authors_author_id', table_name='paper_authors')
    op.drop_table('paper_authors')
    op.drop_index('ix_ingestion_jobs_stage', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_paper_id', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_created_at', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_papers_year', table_name='papers')
    op.drop_index('ix_papers_status', table_name='papers')
    op.drop_index('ix_papers_doi', table_name='papers')
    op.drop_index('ix_papers_created_at', table_name='papers')
    op.drop_index('ix_papers_arxiv_id', table_name='papers')
    op.drop_table('papers')
    op.drop_table('venues')
    op.drop_table('paper_tags')
    op.drop_index('ix_authors_name', table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
